export const ADD_POST_ACTION_TYPE = "ADD_POST_ACTION_TYPE";
export const LIKE_POST_ACTION_TYPE = "LIKE_POST_ACTION_TYPE";
export const ADD_COMMENT_ACTION_TYPE = "ADD_COMMENT_ACTION_TYPE";
export const LIKE_COMMENT_ACTION_TYPE = "LIKE_COMMENT_ACTION_TYPE";
export const EDIT_COMMENT_ACTION_TYPE = "EDIT_COMMENT_ACTION_TYPE";
export const DELETE_COMMENT_ACTION_TYPE = "DELETE_COMMENT_ACTION_TYPE";